import type { Metadata } from 'next'
import { DM_Serif_Display, } from 'next/font/google'
import './globals.css'

const dm = DM_Serif_Display({ 
  weight : ['400'],
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'insure-landing-page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dm.className}>{children}</body>
    </html>
  )
}
